// // Old State
// VoiceState {
//     guild: <ref *1> Guild {
//       id: '1191973790553493514',
//       name: 'los amigitos',
//       icon: 'e9ea2a723606e7bc94d5409bc833d7a9',
//       features: [
//         'SOUNDBOARD',
//         'CHANNEL_ICON_EMOJIS_GENERATED',
//         'ENABLED_MODERATION_EXPERIENCE_FOR_NON_COMMUNITY'
//       ],
//       commands: GuildApplicationCommandManager {
//         permissions: [ApplicationCommandPermissionsManager],
//         guild: [Circular *1]
//       },
//       members: GuildMemberManager { guild: [Circular *1] },
//       channels: GuildChannelManager { guild: [Circular *1] },
//       bans: GuildBanManager { guild: [Circular *1] },
//       roles: RoleManager { guild: [Circular *1] },
//       presences: PresenceManager {},
//       voiceStates: VoiceStateManager { guild: [Circular *1] },
//       stageInstances: StageInstanceManager { guild: [Circular *1] },
//       invites: GuildInviteManager { guild: [Circular *1] },
//       scheduledEvents: GuildScheduledEventManager { guild: [Circular *1] },
//       autoModerationRules: AutoModerationRuleManager { guild: [Circular *1] },
//       available: true,
//       shardId: 0,
//       splash: null,
//       banner: null,
//       description: null,
//       verificationLevel: 0,
//       vanityURLCode: null,
//       nsfwLevel: 0,
//       premiumSubscriptionCount: 0,
//       discoverySplash: null,
//       memberCount: 14,
//       large: false,
//       premiumProgressBarEnabled: false,
//       applicationId: null,
//       afkTimeout: 300,
//       afkChannelId: null,
//       systemChannelId: '1191973791014854756',
//       premiumTier: 0,
//       widgetEnabled: null,
//       widgetChannelId: null,
//       explicitContentFilter: 0,
//       mfaLevel: 0,
//       joinedTimestamp: 1704340234133,
//       defaultMessageNotifications: 0,
//       systemChannelFlags: SystemChannelFlagsBitField { bitfield: 0 },
//       maximumMembers: 500000,
//       maximumPresences: null,
//       maxVideoChannelUsers: 25,
//       maxStageVideoChannelUsers: 50,
//       approximateMemberCount: null,
//       approximatePresenceCount: null,
//       vanityURLUses: null,
//       rulesChannelId: null,
//       publicUpdatesChannelId: null,
//       preferredLocale: 'en-US',
//       safetyAlertsChannelId: null,
//       ownerId: '936831675403468810',
//       emojis: GuildEmojiManager { guild: [Circular *1] },
//       stickers: GuildStickerManager { guild: [Circular *1] }
//     },
//     id: '900835160986099744',
//     serverDeaf: false,
//     serverMute: false,
//     selfDeaf: false,
//     selfMute: true,
//     selfVideo: false,
//     sessionId: '175690342628a4131816661df139f727',
//     streaming: false,
//     channelId: '1191973791014854757',
//     suppress: false,
//     requestToSpeakTimestamp: null
//   }
  



//   // New State
//   VoiceState {
//     guild: <ref *1> Guild {
//       id: '1191973790553493514',
//       name: 'los amigitos',
//       icon: 'e9ea2a723606e7bc94d5409bc833d7a9',
//       features: [
//         'SOUNDBOARD',
//         'CHANNEL_ICON_EMOJIS_GENERATED',
//         'ENABLED_MODERATION_EXPERIENCE_FOR_NON_COMMUNITY'
//       ],
//       commands: GuildApplicationCommandManager {
//         permissions: [ApplicationCommandPermissionsManager],
//         guild: [Circular *1]
//       },
//       members: GuildMemberManager { guild: [Circular *1] },
//       channels: GuildChannelManager { guild: [Circular *1] },
//       bans: GuildBanManager { guild: [Circular *1] },
//       roles: RoleManager { guild: [Circular *1] },
//       presences: PresenceManager {},
//       voiceStates: VoiceStateManager { guild: [Circular *1] },
//       stageInstances: StageInstanceManager { guild: [Circular *1] },
//       invites: GuildInviteManager { guild: [Circular *1] },
//       scheduledEvents: GuildScheduledEventManager { guild: [Circular *1] },
//       autoModerationRules: AutoModerationRuleManager { guild: [Circular *1] },
//       available: true,
//       shardId: 0,
//       splash: null,
//       banner: null,
//       description: null,
//       verificationLevel: 0,
//       vanityURLCode: null,
//       nsfwLevel: 0,
//       premiumSubscriptionCount: 0,
//       discoverySplash: null,
//       memberCount: 14,
//       large: false,
//       premiumProgressBarEnabled: false,
//       applicationId: null,
//       afkTimeout: 300,
//       afkChannelId: null,
//       systemChannelId: '1191973791014854756',
//       premiumTier: 0,
//       widgetEnabled: null,
//       widgetChannelId: null,
//       explicitContentFilter: 0,
//       mfaLevel: 0,
//       joinedTimestamp: 1704340234133,
//       defaultMessageNotifications: 0,
//       systemChannelFlags: SystemChannelFlagsBitField { bitfield: 0 },
//       maximumMembers: 500000,
//       maximumPresences: null,
//       maxVideoChannelUsers: 25,
//       maxStageVideoChannelUsers: 50,
//       approximateMemberCount: null,
//       approximatePresenceCount: null,
//       vanityURLUses: null,
//       rulesChannelId: null,
//       publicUpdatesChannelId: null,
//       preferredLocale: 'en-US',
//       safetyAlertsChannelId: null,
//       ownerId: '936831675403468810',
//       emojis: GuildEmojiManager { guild: [Circular *1] },
//       stickers: GuildStickerManager { guild: [Circular *1] }
//     },
//     id: '900835160986099744',
//     serverDeaf: false,
//     serverMute: false,
//     selfDeaf: false,
//     selfMute: true,
//     selfVideo: false,
//     sessionId: '175690342628a4131816661df139f727',
//     streaming: false,
//     channelId: '1191973791014854757',
//     suppress: false,
//     requestToSpeakTimestamp: null
//   }
  